### ISSUE TITLE
Tracking - Standardized Sender Signatures (MCIP #30)

### ISSUE THREAD

**Issue by cbeck88** [mobilecoinfoundation/mobilecoin#1635]
- [ ] Review and decision on MCIP 18
- [ ] More review and discussion
- [ ] Make mc-crypto-box able to take the ephemeral private key as an argument instead of a PRNG
- [ ] Make the transaction builder feed the tx private key to mc-crypto-box
- [ ] Implement janus test
- [ ] Make the transaction builder return some kind of `SigningContext` for signing blobs with the tx private key
