### ISSUE TITLE
Tracking issue for MCIP #31

### ISSUE THREAD

**Issue by garbageslam** [mobilecoinfoundation/mobilecoin#1733]
This issue is tracking the POC impementation for MCIP https://github.com/mobilecoinfoundation/mcips/pull/31

This is likely two units of work:
- [x] Support "mixed" transactions with multiple token types (https://github.com/mobilecoinfoundation/mobilecoin/pull/1827)
- [x] Support the signed contingent inputs. This means adding support for this in transaction validation, making a `SignedContingentInputBuilder` similar to the transaction builder, and putting it all under test: (https://github.com/mobilecoinfoundation/mobilecoin/pull/1871)
- [x] Tests against a real network: (https://github.com/mobilecoinfoundation/mobilecoin/pull/1979)
