### ISSUE TITLE
Tracking issue for MCIP 52 POC

### ISSUE THREAD

**Issue by cbeck88** [mobilecoinfoundation/mobilecoin#2686]
This is the tracking issue for work connected to [MCIP 52](https://github.com/mobilecoinfoundation/mcips/pull/52)

The work likely has a few steps:
- [x] Implement `TxSummary` and incorporate into `ring_ct::SignatureRctBulletProofs::{sign, verify}`. https://github.com/mobilecoinfoundation/mobilecoin/pull/2683
- [x] Ensure support for SCIs (probably also https://github.com/mobilecoinfoundation/mobilecoin/pull/2683)
- [x] Implement `TxSummaryUnblindingData`, make `TransactionBuilder::build_unsigned` support it, and test this https://github.com/mobilecoinfoundation/mobilecoin/pull/2725
- [x] Improvement to TxSummary: Include input rule digest if input rules are present. This future proofs against the idea that we may want the hardware wallet to have visibility into the input rules. Suggested by Ryan in MCIP 52 review: https://github.com/mobilecoinfoundation/mobilecoin/pull/2809
