### ISSUE TITLE
Tracking issue for nested multi-signature support 

### ISSUE THREAD

**Issue by eranrund** [mobilecoinfoundation/mobilecoin#2693]
We'd like to have the option to specify nested multi-signatures when configuring minting governors and minters. A hypothetical example for this is that we want to be able to express that a `MintConfigTx` needs to be signed by one of two organizations, where each organization requires a 2-out-of-3 to identify itself.

This issue tracks the various steps in getting us there.

- [ ] `mc_crypto_multisig` crate needs to support nested signer sets (https://github.com/mobilecoinfoundation/mobilecoin/pull/2657, https://github.com/mobilecoinfoundation/mobilecoin/pull/2661)
- [ ] Protobuf representation of thew new nested signer set, together with the usual conversion code (https://github.com/mobilecoinfoundation/mobilecoin/pull/2671)
- [ ] `tokens.toml` need to support specifying nested signer sets
- [ ] Ledger/MintTx/MintConfigTx need to support the new nested signer set
- [ ] Tx validation code support for nested signer sets
- [ ] `mc-consensus-mint-client` needs to support nested signer sets (in particular, we need to figure out how to represent them in `MintConfigTxPrefixParams`
