### ISSUE TITLE
Tracking issue for MCIP #59 (Token Metadata document)

### ISSUE THREAD

**Issue by cbeck88** [mobilecoinfoundation/mobilecoin#3049]
In order to implement MCIP #59 there are a few steps:

The following represents backend / foundation work:
- [ ]: Create the file in the correct format, with the correct tokens. This should include token id 0 and token id 1, and probably have an entry for the tokens we minted on testnet at token id 4096.
- [ ]: The file is approved and signed.
- [ ]: The file is hosted at a correct url.

Then, different clients can implement fetching and using this data:
- [ ]: Full-service and desktop wallet can support fetching the file and using the metadata
- [ ]: Moby could support fetching and using the data
- [ ]: Signal could support fetching, validating, and using the data
- [ ]: It's not clear at this time how much functionality connected to validating and interpreting the metadata should be in the android / iOS SDKs.
- [ ]: Reserve auditor can implement fetching the file and using this data
